name: update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: anillc
        authToken: '${{ secrets.CACHIX_TOKEN }}'
    - name: update
      run: |
        nix flake update
        nix run .#update
    - name: build
      run: |
        nix build .
    - uses: stefanzweifel/git-auto-commit-action@v4